window.chapter1Words = [
  ["first","noun","der Anzug","suit"],
  ["first","noun","der Apfelstrudel","apple cake"],
  ["first","noun","die Autobahn","highway"],
  ["first","language","Bulgarisch","Bulgarian"],
  ["first","noun","das Butterbrot","sandwich"],
  ["first","language","Französisch","French"],
  ["first","noun","das Frühstück","breakfast"],
  ["first","adjective","international","international"],
  ["first","language","Italienisch","Italian"],
  ["first","language","Japanisch","Japanese"],
  ["first","noun","der Kranke / die Kranke","sick person"],
  ["first","noun","der Rucksack","backpack"],
  ["first","language","Russisch","Russian"],
  ["first","language","Türkisch","Turkish"],
  ["first","language","Ungarisch","Hungarian"],
  ["first","noun","der Walzer","waltz"],
  ["first","noun","das Würstchen / Würstel","sausage"],
  ["first","verb","zuordnen","to assign"],
  ["first","adjective","andere","other"],
  ["first","verb","kennen","to know someone"],
  ["first","verb","sammeln","to collect"],

  ["greetings","phrase","Bis bald!","See you soon!"],
  ["greetings","phrase","danke","thank you"],
  ["greetings","pronoun","dir","you (informal, dative)"],
  ["greetings","pronoun","du","you (informal)"],
  ["greetings","noun","die Entschuldigung","apology"],
  ["greetings","pronoun","es","it"],
  ["greetings","verb","gehen","to go"],
  ["greetings","adjective","gut","good"],
  ["greetings","phrase","Hallo!","hello"],
  ["greetings","verb","heißen","to be called"],
  ["greetings","verb","hören","to hear"],
  ["greetings","pronoun","ich","I"],
  ["greetings","noun","die Person","person"],
  ["greetings","adjective","sehr","very"],
  ["greetings","phrase","Tschüs!","bye"],
  ["greetings","conjunction","und","and"],
  ["greetings","pronoun","wer?","who?"],
  ["greetings","pronoun","wie?","how?"],
  ["greetings","phrase","Wie geht's?","How are you?"],
  ["greetings","adjective","auch","also"],
  ["greetings","verb","sein","to be"],
  ["greetings","phrase","Auf Wiedersehen!","goodbye"],
  ["greetings","pronoun","das","this / that"],
  ["greetings","noun","die Frau","woman"],
  ["greetings","phrase","Gute Nacht!","good night"],
  ["greetings","phrase","Guten Abend!","good evening"],
  ["greetings","phrase","Guten Morgen!","good morning"],
  ["greetings","phrase","Guten Tag!","good day / hello"],
  ["greetings","noun","der Herr","gentleman"],
  ["greetings","pronoun","Ihnen","you (formal, dative)"],
  ["greetings","noun","die Kollegin","female colleague"],
  ["greetings","pronoun","mein / meine","my"],
  ["greetings","noun","der Name","name"],
  ["greetings","pronoun","Sie","you (formal)"],
  ["greetings","noun","der Dialog","dialogue"],

  ["introductions","phrase","Wie heißen Sie?","What is your name?"],
  ["introductions","noun","die Antwort","answer"],
  ["introductions","preposition","aus","from"],
  ["introductions","language","Deutsch","German"],
  ["introductions","place","Deutschland","Germany"],
  ["introductions","language","Englisch","English"],
  ["introductions","preposition","in","in"],
  ["introductions","verb","kommen","to come from"],
  ["introductions","noun","der Reiseführer","travel guide"],
  ["introductions","language","Spanisch","Spanish"],
  ["introductions","verb","sprechen","to speak"],
  ["introductions","noun","das Telefon","telephone"],
  ["introductions","pronoun","welche? / welches?","which?"],
  ["introductions","pronoun","wo?","where?"],
  ["introductions","pronoun","woher?","from where?"],
  ["introductions","verb","wohnen","to live"],
  ["introductions","pronoun","sie","she"],
  ["introductions","pronoun","er","he"],
  ["introductions","verb","ergänzen","to complete"],
  ["introductions","noun","die Hausnummer","house number"],
  ["introductions","noun","die Postleitzahl","postal code"],
  ["introductions","noun","die Webseite","website"],
  ["introductions","noun","das Interview","interview"],
  ["introductions","verb","notieren","to note down"],
  ["introductions","noun","der Partner","male partner"],
  ["introductions","noun","die Partnerin","female partner"],
  ["introductions","verb","raten","to guess"],
  ["introductions","verb","vorstellen","to introduce"],

  ["world","noun","der Buchstabe","letter"],
  ["world","adjective","laut","loud / loudly"],
  ["world","noun","die Zahl","number"],
  ["world","verb","fragen","to ask"],
  ["world","noun","die Handynummer","cell phone number"],
  ["world","pronoun","Ihr / Ihre","your (formal) / her"],
  ["world","noun","die Telefonnummer","telephone number"],
  ["world","noun","das Alphabet","alphabet"],
  ["world","adjective","erst","first"],
  ["world","verb","schreiben","to write"],
  ["world","phrase","bitte","please"],
  ["world","verb","buchstabieren","to spell"],
  ["world","pronoun","dein / deine","your (informal)"],
  ["world","adjective","ein bisschen","a little"],
  ["world","noun","die E-Mail-Adresse","email address"],
  ["world","verb","können","to be able to"],
  ["world","adjective","langsam","slowly"],
  ["world","adjective","nicht","not"],
  ["world","phrase","noch einmal","once more"],
  ["world","verb","variieren","to vary"],
  ["world","verb","verstehen","to understand"],
  ["world","phrase","Wie bitte?","Come again?"],
  ["world","language","Arabisch","Arabic"],
  ["world","place","China","China"],
  ["world","language","Chinesisch","Chinese"],
  ["world","verb","lernen","to learn"],
  ["world","place","Österreich","Austria"],
  ["world","noun","die Tabelle","table / chart"],
  ["world","place","die USA","the USA"],
  ["world","place","Frankreich","France"],
  ["world","place","Großbritannien","Great Britain"],
  ["world","place","Italien","Italy"],
  ["world","place","Japan","Japan"],
  ["world","noun","das Land","country"],
  ["world","place","Polen","Poland"],
  ["world","language","Polnisch","Polish"],
  ["world","language","Rätoromanisch","Romansh"],
  ["world","place","Russland","Russia"],
  ["world","place","die Schweiz","Switzerland"],
  ["world","place","Spanien","Spain"],
  ["world","noun","die Sprache","language"],
  ["world","place","die Türkei","Turkey"],
  ["world","place","Schweden","Sweden"],
  ["world","place","die Ukraine","Ukraine"],
  ["world","noun","die E-Mail","email"],
  ["world","place","Portugal","Portugal"],
  ["world","place","Griechenland","Greece"],
  ["world","language","Griechisch","Greek"],
  ["world","place","Irland","Ireland"],
  ["world","place","Kanada","Canada"],
  ["world","language","Maori","Maori"],
  ["world","place","Mexiko","Mexico"],
  ["world","place","Neuseeland","New Zealand"],
  ["world","language","Portugiesisch","Portuguese"],
  ["world","language","Schwedisch","Swedish"],
  ["world","place","Syrien","Syria"],
  ["world","language","Thai","Thai"],
  ["world","place","Thailand","Thailand"],
  ["world","noun","der Film","film / movie"],
  ["world","adjective","klar","clear"]
];